// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.commands;

// import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.CommandGroup;
// import frc.robot.Robot;
// import frc.robot.subsystems.*;
// import frc.robot.commands.*;
// import frc.robot.Dash.*;

/**
 *
 */
public class GoToGroup extends CommandGroup {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
    public GoToGroup(double x, double y) {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
        
        
        //this is the distance we need to go
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
    addSequential(new goToCalculation(x,y));
    addSequential(new TurnToGyroAngle()); //will grab angle from Robot.angle
    addSequential(new driveForFeet()); //will grab distance from Robot.distance

        
    } 
    // public double createDistance(double xLength, double yLength,double hyp) {
    //     double distance;
    //     if (yLength == 0){
    //         distance = xLength;
    //     } else if (xLength == 0){
    //         distance = yLength;
    //     }else{
    //         distance = hyp;
    //     }
    //     return distance;
    // }

    
}
